### ISSUE TITLE
C2: Return error when no GPU is available

### ISSUE THREAD

**Issue by vmx** [supranational/supra_seal#10]
When no GPU is available, the proofs might return wrong results. Instead of doing that, there should be an error that no GPU is available.

This issue is a spin-off of https://github.com/supranational/supra_seal/issues/9#issuecomment-1594462821, so that it doesn't become forgotten.

**Comment by dot-asm** [comment]
This is supposed to be resolved in 57f2f0a3b8ee2aa83ba78e77c20018de0db7a99d.

**Comment by vmx** [comment]
Thanks, closing then!
