### ISSUE TITLE
Standalone PC2: wrong encoding

### ISSUE THREAD

**Issue by vmx** [supranational/supra_seal#11]
I've been trying out the new standalone PC2 binary. When I run it on existing data (created with `benchy`), I get the correct TreeC files, but I get different TreeR as well as a different sealed file. I wonder if I'm doing something wrong.

To reproduce first do a `benchy` run that preserves the data. Please adapt the path where to store things (also in the commands below), you'll need around 500GiB of storage.

```console
git clone https://github.com/filecoin-project/rust-fil-proofs
cd rust-fil-proofs
RUST_LOG=trace FIL_PROOFS_USE_MULTICORE_SDR=1 FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1 FIL_PROOFS_USE_GPU_TREE_BUILDER=1 FIL_PROOFS_VERIFY_CACHE=0 RUSTFLAGS="-C target-cpu=native" /usr/bin/time -v cargo run --release --bin benchy --features cuda -- window-post --size 32gib --cache /tmp/window-post-32gib-dir  --preserve-cache
```

Now you can run PC2 on it again. Please note that the `sealed-file` needs to be a copy of the `staged-file` before PC2 is run, as PC2 manipulates the file in place. Then run `benchy` with PC2 only:

```console
cp /tmp/window-post-32gib-dir/staged-file /tmp/window-post-32gib-dir/sealed-file 
RUST_LOG=trace FIL_PROOFS_USE_MULTICORE_SDR=1 FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1 FIL_PROOFS_USE_GPU_TREE_BUILDER=1 FIL_PROOFS_VERIFY_CACHE=0 RUSTFLAGS="-C target-cpu=native" /usr/bin/time -v cargo run --release --bin benchy --features cuda -- window-post --size 32gib --cache /tmp/window-post-32gib-dir --skip-precommit-phase1 --skip-commit-phase1 --skip-commit-phase2
```

I ran the standalone PC2 binary via:

```
time ./bin/pc2 -d /storage/d2/vmx/window-post-32gib-dir/staged-file -i /storage/d2/vmx/window-post-32gib-dir -o /storage/d2/vmx/supraseal_pc2
```

The resulting `sealed-file` have different checksums, the TreeRs as well. The TreeCs are correct.

**Comment by simonatsn** [comment]
This should be fixed in the latest commit.
