### ISSUE TITLE
PC2 tool: different sector sizes

### ISSUE THREAD

**Issue by vmx** [supranational/supra_seal#17]
As I understand is the [pc2 tool](https://github.com/supranational/supra_seal/blob/242fad55ab987c108115ef71505702cb9c977247/tools/pc2.cu) the successor of [pc2_cuda](https://github.com/supranational/pc2_cuda/).

The new tool is missing an option to set the sector size (like the old one did). This is crucial for integration, so that it can be tested on smaller sector sizes. Please add an option so that I'm able to set the sector size.

**Comment by simonatsn** [comment]
This is supported as part of the build flow. Running:

`build.sh 512MiB`

Will build pc2 with support for 512MiB sectors.

**Comment by vmx** [comment]
> Will build pc2 with support for 512MiB sectors.

Yes, but I'd prefer a runtime flag. It would be inconvenient to have different binaries for the different sector sizes.

**Comment by simonatsn** [comment]
I took a look at what it would take to support this. My concern with supporting all sectors sizes at runtime is that we would need to make sector size part of the compile time template. This will generate a significant amount of code through templates and may negatively impact compile time. Which sector sizes are important for testing?

**Comment by vmx** [comment]
Ideally all sector sizes we support (also the test sizes). That would be: 2KiB, 4KiB, 16KiB, 32KiB, 8MiB, 16MiB, 512MiB, 1GiB, 32GiB, 64GiB.

Important ones for testing for proofs (I'll also ask the Lotus team) are: 2KiB, 4KiB, 16KiB, 32KiB, 512MiB, 32GiB, 64GiB.

I'm not concerned about the compile time, I'd just go with all of them. If you are concerned, perhaps it could be a flag, where you either compile for production sized (32GiB and 64GiB), or including all testing sizes.

**Comment by vmx** [comment]
With https://github.com/supranational/supra_seal/pull/40 merged, this is now possible, hence closing this issue.
