### ISSUE TITLE
C2: make it compile with blst 0.3.11

### ISSUE THREAD

**Issue by vmx** [supranational/supra_seal#21]
`supraseal-c2` requires `blst` 0.3.11. Though it cannot be upgraded as the tests depend on Filecoin crates that pin blst to version 0.3.10. I've prepared a branch in `blstrs` (this is what pulls in the `blst` dependency), which relaxes the version requirement.

That branch combined with using newer versions of proofs makes things compile. The diff looks like that:

```diff
--- a/c2/Cargo.toml
+++ b/c2/Cargo.toml
@@ -4,15 +4,15 @@ version = "0.1.0"
 edition = "2021"
 
 [dependencies]
-blst = "^0.3.9"
+blst = "^0.3.11"
 sppark = "^0.1.3"
 
 [dev-dependencies]
 anyhow = "1.0.26"
 bincode = "1.1.2"
-filecoin-proofs-api = "14.0.0"
-filecoin-proofs-v1 = { package = "filecoin-proofs", version = "~14.0.0", default-features = false }
-storage-proofs-core = { version = "~14.0.0", default-features = false }
+filecoin-proofs-api = "15.0.0"
+filecoin-proofs-v1 = { package = "filecoin-proofs", version = "15.0.0", default-features = false }
+storage-proofs-core = { version = "15.0.0", default-features = false }
 
 [features]
 default = []
@@ -27,3 +27,6 @@ quiet = []
 [build-dependencies]
 cc = { version = "^1.0.70", features = ["parallel"] }
 which = "^4.0"
+
+[patch.crates-io]
+blstrs = { git = "https://github.com/filecoin-project/blstrs", branch = "blst-0310-or-newer" }
```

Those new Filecoin crates depend on `bellperson` 0.25. So the patch would be need to be adapted.

Given that the tests are meant to show how this code can be used with `bellperson`, Once there is a release of `supraseal-c2`, we can merge https://github.com/filecoin-project/bellperson/pull/308, so it will be integrated into `bellperson`. I don't think we then need a usage example anymore, as the best example is the integration itself.

In order to speed up the process of a release and unbreaking this build (you can just point to `blst` 0.3.11 directly), I propose to just remove the whole `test` directory and all its dependencies.

**Comment by dot-asm** [comment]
Could you double-check #26?

**Comment by dot-asm** [comment]
#26 is merged.
