### ISSUE TITLE
TreeD binary cannot be compiled

### ISSUE THREAD

**Issue by vmx** [supranational/supra_seal#43]
The tree_d binary in `tools` cannot be compiled. There are several errors. `tree_c` works. It would be great to have the compilation steps for `tree_d` also added to the `build.sh`.

**Comment by sean-sn** [comment]
Pushed a quick fix for tree_d. See if that works for you now. The file and command to build got a little stale with the movement of parameters and instantiation.

**Comment by vmx** [comment]
Oh wow that was insanely fast! Thanks a lot, that works for me.
