### ISSUE TITLE
C2 failure on rust-fil-proofs test

### ISSUE THREAD

**Issue by vmx** [supranational/supra_seal#5]
In my SupraSeal C2 integration work for `rust-fil-proofs` I ran into a failing test, it sefaults. Here are the steps to reproduce:

```console
git clone https://github.com/filecoin-project/rust-fil-proofs --branch sn-c2
cd rust-fil-proofs
RUST_LOG=trace cargo test --no-default-features --features supraseal --package filecoin-proofs --test api test_window_post_partition_matching_2kib_base_8 -- --nocapture --test-threads=1
```

It works when run with e.g. OpenCL `RUST_LOG=trace cargo test --no-default-features --features opencl --package filecoin-proofs --test api test_window_post_partition_matching_2kib_base_8 -- --nocapture --test-threads=1`

**Comment by sandsentinel** [comment]
This is another case of the SRS file not being read before the proof.

`"/var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0170db1f394b35d995252228ee359194b13199d259380541dc529fb0099096b0.params"` is the SRS file that's being used on my end, and reading that with `supraseal_c2::read_srs(String::from("..."));` somewhere before the proof fixes the issue and tests pass.

**Comment by vmx** [comment]
Good catch, sorry for the noise. I need to make sure that reading in the parameters is always in the code path, even for tests.

I guess as mentioned [in the other isssue](https://github.com/supranational/supra_seal/issues/2#issuecomment-1561158797), an error message would help :)
