### ISSUE TITLE
Build errors on Ubuntu 20.04 and GCC 9

### ISSUE THREAD

**Issue by ramin-raeisi** [supranational/supra_seal#6]
Hi,

I had build errors, so I installed gcc-11, yet still two modifications were still needed as follow:

1. Adding `-lpthread` to https://github.com/supranational/supra_seal/blob/main/build.sh#L192 line due to `undefined reference to pthread_create`
2. Adding `-std=c++17` to https://github.com/supranational/supra_seal/blob/main/build.sh#L196 due to C++ compilation errors

Finally it successfully got built.

**Comment by dot-asm** [comment]
Thanks!
